services:

  # ===================== #
  # ===== OPENWEBUI ===== #
  # ===================== #
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    env_file:
      - .env.webui
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - CoreAgent


  # ==================== #
  # ===== DATABASE ===== #
  # ==================== #
  db:
    image: postgres:18
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.db
    networks:
      - CoreAgent


  # ===================== #
  # ===== LLAMA.CPP ===== #
  # ===================== #
  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    ports:
      - 8081:8081
    volumes:
      - ./models:/models
    environment:
      # Khai báo đường dẫn chứa các file .so để hệ thống tìm thấy libllama-common.so.0
      - LD_LIBRARY_PATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      -m /models/Qwen3.5-2B-Q4_K_M.gguf
      -ngl 99
      -t 6
      --ctx-size 8192
      -fa on
      --reasoning off
      --host 0.0.0.0
      --port 8081
    networks:
      - CoreAgent


  # =================== #
  # ===== SEARXNG ===== #
  # =================== #
  searxng-core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      - 8082:8082
    env_file: 
      - .env.searxng
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - core-data:/var/cache/searxng/
    networks:
      - CoreAgent
  searxng-valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - valkey-data:/data/
    networks:
      - CoreAgent


# =================== #
# ===== VOLUMES ===== #
# =================== #
volumes:
  open-webui:
  db:
  llama-cpp:
  core-data:
  valkey-data:

# ==================== #
# ===== NETWORKS ===== #
# ==================== #
networks:
  CoreAgent: